/**
 * Build-time reference generation (decision D11): the layout gallery,
 * widget registry, and spec JSON Schema are written from @alpona/core, so
 * the docs can never drift from the code. Run before `astro build`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { layoutTemplates, widgetDefinitions } from '@alpona/core';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../src/content/docs/reference');
const coreSchema = resolve(here, '../../packages/core/src/schema/dashboard-spec.schema.json');
mkdirSync(outDir, { recursive: true });

const GENERATED = '<!-- generated by scripts/gen-reference.ts — do not edit by hand -->';

/** A small SVG preview of a layout's slot regions on its grid. */
function layoutSvg(layout: (typeof layoutTemplates)[number]): string {
  const cols = layout.columns ?? 12;
  const rows = Math.max(...layout.slots.map((s) => s.region.y + s.region.h), 1);
  const cw = 30;
  const rh = 22;
  const gap = 4;
  const w = cols * cw;
  const h = rows * rh;
  const cells = layout.slots
    .map((s) => {
      const x = s.region.x * cw + gap / 2;
      const y = s.region.y * rh + gap / 2;
      const rw = s.region.w * cw - gap;
      const rh2 = s.region.h * rh - gap;
      return `<rect x="${x}" y="${y}" width="${rw}" height="${rh2}" rx="4" fill="#211720" stroke="#c96a4a" stroke-width="1"/><text x="${x + rw / 2}" y="${y + rh2 / 2 + 3}" fill="#bcaa93" font-size="9" font-family="monospace" text-anchor="middle">${s.id}</text>`;
    })
    .join('');
  return `<svg viewBox="0 0 ${w} ${h}" width="100%" style="max-width:520px;background:#130e12;border:1px solid #372a33;border-radius:10px;padding:6px" role="img" aria-label="${layout.name} layout">${cells}</svg>`;
}

// ── Layout gallery ─────────────────────────────────────────────────
const layoutsMd = [
  '---',
  'title: Layout gallery',
  'description: Every layout template, generated from the registry.',
  'sidebar: { order: 1 }',
  '---',
  '',
  GENERATED,
  '',
  `Alpona ships **${layoutTemplates.length}** layout templates. The planner picks one; the composer fills its slots and enforces the contract. Each is a single JSON file — see [Adding a layout](/extending/layouts).`,
  '',
  ...layoutTemplates.flatMap((l) => {
    const rows = l.slots
      .map(
        (s) =>
          `| \`${s.id}\` | ${s.role} | ${s.accepts.length ? s.accepts.map((a) => `\`${a}\``).join(', ') : 'any'} | ${s.minWidgets}–${s.maxWidgets} | ${s.overflow} |`,
      )
      .join('\n');
    return [
      `## ${l.name}@${l.version}`,
      '',
      l.whenToUse ?? l.description ?? '',
      '',
      layoutSvg(l),
      '',
      '| Slot | Role | Accepts | Count | Overflow |',
      '| --- | --- | --- | --- | --- |',
      rows,
      '',
    ];
  }),
].join('\n');
writeFileSync(join(outDir, 'layouts.md'), layoutsMd);

// ── Widget registry ────────────────────────────────────────────────
const widgetsMd = [
  '---',
  'title: Widget registry',
  'description: Every widget type, its result-shape contract, and agent hints.',
  'sidebar: { order: 2 }',
  '---',
  '',
  GENERATED,
  '',
  `**${widgetDefinitions.length}** widget types. Each declares a \`resultShape\` contract — which SQL columns map onto which visual roles — that the binder must satisfy. See [Adding a widget](/extending/widgets).`,
  '',
  ...widgetDefinitions.flatMap((w) => {
    const shape = (keys: string[]) =>
      keys.length
        ? keys.map((k) => `\`${k}\` — ${w.resultShape.docs[k] ?? ''}`).join('; ')
        : '—';
    return [
      `## ${w.type}`,
      '',
      w.description,
      '',
      `**Required:** ${shape(w.resultShape.required)}`,
      '',
      w.resultShape.optional.length ? `**Optional:** ${shape(w.resultShape.optional)}` : '',
      '',
      `**When to use:** ${w.agentHints.whenToUse}`,
      '',
      `**SQL guidance:** ${w.agentHints.sqlGuidance}`,
      '',
    ].filter((line) => line !== '');
  }),
].join('\n');
writeFileSync(join(outDir, 'widgets.md'), widgetsMd);

// ── Spec JSON Schema ───────────────────────────────────────────────
const schema = readFileSync(coreSchema, 'utf8');
const schemaMd = [
  '---',
  'title: DashboardSpec JSON Schema',
  'description: The schema every spec is validated against.',
  'sidebar: { order: 3 }',
  '---',
  '',
  GENERATED,
  '',
  'Every spec the agent produces — and every refinement — passes this schema before it renders. It is the agent output gate and the interpreter contract.',
  '',
  '```json',
  schema.trimEnd(),
  '```',
  '',
].join('\n');
writeFileSync(join(outDir, 'spec-schema.md'), schemaMd);

console.log(
  `◈ reference generated: ${layoutTemplates.length} layouts, ${widgetDefinitions.length} widgets, 1 schema`,
);
