import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export type AgentProvider = 'anthropic' | 'openai';

export interface ServerConfig {
  port: number;
  /** Connection string: postgres://… or duckdb:<path>. */
  db: string;
  /** Path to the data dictionary JSON generated by alpona. */
  dictionaryPath: string;
  mock: boolean;
  provider: AgentProvider;
  anthropicApiKey: string | undefined;
  openaiApiKey: string | undefined;
  /** OpenAI-compatible endpoint override (LM Studio, vLLM, Ollama…). */
  openaiBaseUrl: string | undefined;
  plannerModel: string;
  binderModel: string;
  copyModel: string;
  /** Hard row cap enforced on every query. */
  maxRows: number;
  /** Per-query statement timeout in ms. */
  queryTimeoutMs: number;
  /** Directory for saved dashboards (the share-URL store). */
  dataDir: string;
  /** Directory of canned report JSON seeds ({name, prompt?, spec}). */
  seedReportsDir: string;
  /** Postgres connection for the specs store (Supabase deploy mode).
   *  Unset → zero-infra file store. */
  specsDb: string | undefined;
  /** Display name for the active ALPONA_DB source. */
  sourceName: string;
  /** Sources registry written by `alpona connect`. */
  sourcesPath: string;
  /** When set, serve this built-studio directory from the same origin. */
  studioDir: string | undefined;
  /** Request authentication: none (playground) | apikey | oidc. */
  authMode: 'none' | 'apikey' | 'oidc';
  apiKey: string | undefined;
  oidcIssuer: string | undefined;
  oidcAudience: string | undefined;
  oidcJwksUrl: string | undefined;
  /** HS256 shared secret (Supabase GoTrue self-hosted). */
  jwtSecret: string | undefined;
  /** Public URL the studio reaches the auth service at (login page). */
  authUrl: string | undefined;
  /** Internal GoTrue base URL to reverse-proxy /auth/v1/* to. */
  authUpstream: string | undefined;
}

/** Walks up from cwd to the pnpm workspace root (falls back to cwd). */
export function workspaceRoot(from: string = process.cwd()): string {
  let dir = resolve(from);
  for (;;) {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) return resolve(from);
    dir = parent;
  }
}

/** Loads .env from the workspace root when present (dev convenience). */
export function loadDotEnv(): void {
  const path = join(workspaceRoot(), '.env');
  if (existsSync(path)) {
    try {
      process.loadEnvFile(path);
    } catch {
      // best effort — explicit env always wins
    }
  }
}

/** Per-provider stage defaults: fast model for planner/copy, strong for binders. */
const MODEL_DEFAULTS: Record<AgentProvider, { planner: string; binder: string; copy: string }> = {
  anthropic: { planner: 'claude-haiku-4-5', binder: 'claude-opus-4-8', copy: 'claude-haiku-4-5' },
  openai: { planner: 'gpt-5.4-mini', binder: 'gpt-5.4', copy: 'gpt-5.4-mini' },
};

export function loadConfig(env: NodeJS.ProcessEnv = process.env): ServerConfig {
  const root = workspaceRoot();
  const defaultDuckDb = join(root, 'datasets/supply-chain/db/alpona.duckdb');
  const defaultDictionary = join(root, 'datasets/supply-chain/db/dictionary/dictionary.json');

  // Provider: explicit ALPONA_PROVIDER wins; otherwise whichever has
  // credentials, Anthropic first. A base URL alone counts for OpenAI —
  // local servers like LM Studio need no key.
  const anthropicConfigured = Boolean(env.ANTHROPIC_API_KEY);
  const openaiConfigured = Boolean(env.OPENAI_API_KEY || env.OPENAI_BASE_URL);
  const explicit = env.ALPONA_PROVIDER;
  const provider: AgentProvider =
    explicit === 'anthropic' || explicit === 'openai'
      ? explicit
      : openaiConfigured && !anthropicConfigured
        ? 'openai'
        : 'anthropic';
  const configured = provider === 'anthropic' ? anthropicConfigured : openaiConfigured;
  const defaults = MODEL_DEFAULTS[provider];

  return {
    port: Number(env.ALPONA_PORT ?? 3001),
    db: env.ALPONA_DB ?? `duckdb:${defaultDuckDb}`,
    dictionaryPath: env.ALPONA_DICTIONARY ?? defaultDictionary,
    mock: env.ALPONA_MOCK === '1' || (!configured && env.ALPONA_MOCK !== '0'),
    provider,
    anthropicApiKey: env.ANTHROPIC_API_KEY || undefined,
    openaiApiKey: env.OPENAI_API_KEY || undefined,
    openaiBaseUrl: env.OPENAI_BASE_URL || undefined,
    // `||` (not `??`) so an empty env var — e.g. a compose passthrough left
    // unset — falls back to the per-provider default rather than blanking it.
    plannerModel: env.ALPONA_PLANNER_MODEL || defaults.planner,
    binderModel: env.ALPONA_BINDER_MODEL || defaults.binder,
    copyModel: env.ALPONA_COPY_MODEL || defaults.copy,
    maxRows: Number(env.ALPONA_MAX_ROWS ?? 1000),
    queryTimeoutMs: Number(env.ALPONA_QUERY_TIMEOUT_MS ?? 5000),
    dataDir: env.ALPONA_DATA_DIR ?? join(root, '.alpona/dashboards'),
    // Convention: canned reports live in <example>/reports, next to <example>/db.
    seedReportsDir: env.ALPONA_SEED_REPORTS ?? join(root, 'datasets/supply-chain/reports'),
    specsDb: env.ALPONA_SPECS_DB || undefined,
    sourceName: env.ALPONA_SOURCE_NAME ?? 'supply-chain',
    sourcesPath: env.ALPONA_SOURCES ?? join(root, '.alpona/sources.json'),
    studioDir: env.ALPONA_STUDIO_DIR || undefined,
    authMode:
      env.AUTH_MODE === 'apikey' || env.AUTH_MODE === 'oidc'
        ? env.AUTH_MODE
        : // Playground default — and an explicit guard against typos
          // silently disabling auth someone thought they enabled.
          (() => {
            if (env.AUTH_MODE && env.AUTH_MODE !== 'none') {
              throw new Error(`unknown AUTH_MODE "${env.AUTH_MODE}" (none | apikey | oidc)`);
            }
            return 'none' as const;
          })(),
    apiKey: env.ALPONA_API_KEY || undefined,
    oidcIssuer: env.OIDC_ISSUER || undefined,
    oidcAudience: env.OIDC_AUDIENCE || undefined,
    oidcJwksUrl: env.OIDC_JWKS_URL || undefined,
    jwtSecret: env.ALPONA_JWT_SECRET || undefined,
    // When proxying GoTrue, the studio uses the same-origin path; an
    // explicit ALPONA_AUTH_URL still wins for external auth services.
    authUrl: env.ALPONA_AUTH_URL || (env.ALPONA_AUTH_UPSTREAM ? '/auth/v1' : undefined),
    authUpstream: env.ALPONA_AUTH_UPSTREAM || undefined,
  };
}
